name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Executa para qualquer branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set branch name (formata para tag Docker válida)
        id: vars
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "branch_name=$SAFE_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: youruser/yourimage:${{ steps.vars.outputs.branch_name }}
